# Generated by Django 3.2.16 on 2024-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241102_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
