# Generated by Django 3.2.16 on 2024-10-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
